# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - dfberry-test
# version: 0.0.1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'



      # Build server production into dist
      - name: Server - install, build
        run: |
          cd website-1
          npm install
          npm run build --if-present
          npm run test --if-present
          mkdir client

      # Build client production into /prod directory
      - name: Client - install, build
        run: |
          cd client-1
          npm install
          npm run build:prod --if-present
          ls -la prod
          mv prod/*.* ../website-1/client
          ls -la ../website-1/client

      # Copy everything except node_modules
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: |
            ./website-1
            !**/node_modules

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'knwgo1'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EF1532115535490FBC296EAFB1E6A3F7 }}
          package: .
